-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 04, 2015 at 11:26 AM
-- Server version: 5.6.19-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `iitbxblended_useit`
--

-- --------------------------------------------------------

--
-- Table structure for table `SIP_reports`
--

CREATE TABLE IF NOT EXISTS `SIP_reports` (
  `reportid` varchar(20) NOT NULL,
  `usertype` int(11) NOT NULL,
  `sqlquery` text,
  `report_title` varchar(100) NOT NULL,
  `comments` varchar(200) NOT NULL,
  `num_cols` int(11) DEFAULT '1',
  PRIMARY KEY (`reportid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `SIP_reports`
--

INSERT INTO `SIP_reports` (`reportid`, `usertype`, `sqlquery`, `report_title`, `comments`, `num_cols`) VALUES
('1', 0, 'select 0 AS id,"Email" as''A'',"Full Name" as''B'' ,"Institute Name" as''C'' ,"Course" as''D'',"IITBX Login" as''E'' ,"BMS Login" as ''F'' union all select (@cnt := @cnt + 1) AS id,query.Email,query.Full_Name,query.Institute_Name,query.Course,query.IITBX_Login,query.BMS_Login  from (SELECT p.email as Email, concat(p.firstname,p.lastname) as Full_Name, i.institutename as Institute_Name,ec.coursename as Course,if(a.email is null, "Does Not Exists","Exists") "IITBX_Login",if(l.status=0,"Does Not Activated","Activated") "BMS_Login" from SIP_personinformation p LEFT OUTER JOIN edxapp.auth_user a on a.email=p.email,SIP_courselevelusers c,SIP_edxcourses ec, SIP_t10kt_institute i ,SIP_userlogin l,auth_user au where c.roleid=5 and c.courseid_id=ec.id and c.personid_id=p.id and p.instituteid_id=i.instituteid and l.user_id=au.id and p.email=au.email and i.instituteid != 0 order by i.institutename,ec.coursename) as query CROSS JOIN (SELECT @cnt := 0) AS dummy; ', 'Teachers: Status Report', 'Displays the List of Active Teachers in the Blended MOOCs System', 6),
('10', 0, 'select 0 AS id,"Course" as A,"Under 18" as''B'',"18-30" as''C'' ,"30-60" as ''D'' ,"Above 60" as''E'',"No Data" as ''F'',"Total" as "G" union all  select (@cnt := @cnt + 1) AS id,query.course_id,query.p,query.q,query.r,query.s,query.t,query.Total from (SELECT course_id,sum(if(age_group ="under 18",1,0)) p,\r\nsum(if(age_group ="18-30",1,0)) q,\r\nsum(if(age_group ="30-60",1,0)) r,\r\nsum(if(age_group ="above 60",1,0)) s,\r\nsum(if(age_group ="ND",1,0)) t,\r\ncount(*) "Total"\r\nfrom\r\n(SELECT a.user_id, a.course_id, if( year_of_birth <1955, "above 60", if( year_of_birth <1985, "30-60", if( year_of_birth <1997, "18-30", if( year_of_birth <2015, "under 18", "ND" ) ) ) ) "age_group"\r\nFROM edxapp.student_courseenrollment a, edxapp.auth_userprofile b\r\nWHERE a.course_id\r\nIN (\r\n''IITBombayX/ME209xA15/2015_T1'', ''IITBombayX/EE210.1xA15/2015_T1'', ''IITBombayX/CS101.1xA15/2015_T1''\r\n)\r\nAND a.user_id = b.user_id and a.is_active=1\r\n)  users group by course_id)query  CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'User Profile: Age-group wise', 'User Profile: Age-group wise', 7),
('11', 0, 'select 0 AS id,"course_id" as A,"Associates" as "B","Bachelors''" as "C","Masters''" as "D","Doctrate" as "E","School" as "F","Others" as "G","No Data" as "H","Total" as "I" union all select (@cnt:= @cnt+1) as id,query.course_id,query.p,query.q,query.r,query.s,query.t,query.u,query.v,query.Total from\r\n(SELECT course_id,\r\nsum(if(level_of_education=''a'',1,0)) p,\r\nsum(if(level_of_education=''b'',1,0)) q ,\r\nsum(if(level_of_education=''m'',1,0)) r,\r\nsum(if(level_of_education=''p'',1,0)) s ,\r\nsum(if(level_of_education in (''el'',''hs'',''jhs''),1,0)) t,\r\nsum(if(level_of_education=''other'',1,0)) u ,\r\nsum(if(level_of_education not in (''el'',''hs'',''jhs'',''a'',''b'',''m'',''p'',''other'') or level_of_education is null,1,0)) v,\r\ncount(*) "Total"\r\nfrom\r\n(SELECT a.user_id, a.course_id,level_of_education \r\nFROM edxapp.student_courseenrollment a, edxapp.auth_userprofile b\r\nWHERE a.course_id\r\nIN (\r\n''IITBombayX/ME209xA15/2015_T1'', ''IITBombayX/EE210.1xA15/2015_T1'', ''IITBombayX/CS101.1xA15/2015_T1''\r\n)\r\nAND a.user_id = b.user_id and a.is_active=1\r\n)  users group by course_id)query  CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'User Profile: Level of Education', 'User Profile: Level of Education', 9),
('12', 0, 'select 0 AS id,"Course" as "A","States" as "B","Cities" as "C", "Distinct PIN" as "D","Disclosed Aadhar Id" as "E" union all select (@cnt:=@cnt+1) as id, query.course_id,query.p,query.q,query.r,query.s from ( SELECT course_id,\r\ncount(distinct State)  as p,\r\ncount(distinct City)  as q,\r\ncount(distinct pincode)  as r ,\r\ncount(distinct aadhar_id) as s\r\nfrom\r\n(SELECT a.user_id, a.course_id, e.name "City", d.name "State", c.pincode, c.aadhar_id\r\nFROM edxapp.student_courseenrollment a, edxapp.auth_userprofile b, edxapp.student_mooc_person c, edxapp.student_mooc_state d, edxapp.student_mooc_city e\r\nWHERE a.course_id\r\nIN (\r\n''IITBombayX/ME209xA15/2015_T1'', ''IITBombayX/EE210.1xA15/2015_T1'', ''IITBombayX/CS101.1xA15/2015_T1''\r\n)\r\nAND a.user_id = b.user_id\r\nAND a.user_id = c.user_id\r\nAND c.state_id = d.id\r\nAND c.city_id = e.id\r\n)  users group by course_id)query CROSS JOIN (SELECT @cnt :=0) AS dummy;', 'Geographical Diversity', 'Area-based Enrollment', 5),
('13', 0, 'select 0 AS id,"Institute Name" as A,"Course" as B,"Teacher''s Name" as C ,"Teacher''s Email" as D, "Student''s Rollno" as E ,"Student''s Email" as F,"Stud Username" as G\n union all\nselect (@cnt := @cnt + 1) AS id,query.institutename,query.courseid,query.full_name,query.email,query.roll_no,query.stud_email,query.username\nFROM\n(SELECT t.institutename, s.courseid, concat( p.firstname, '' '', p.lastname ) full_name, p.email, s.roll_no, i.email stud_email, i.username\nFROM SIP_studentdetails s, SIP_iitbx_auth_user i, SIP_courselevelusers c, SIP_personinformation p, SIP_t10kt_institute t\nWHERE s.edxuserid_id = i.edxuserid\nAND s.edxis_active =1\nAND s.teacherid_id = c.id\nAND c.personid_id !=1\nAND p.id = c.personid_id\nAND t.instituteid = c.instituteid_id) query CROSS JOIN (SELECT @cnt := 0) AS dummy', 'Teachers'' Students Association Detail Report', 'List of all MOOCS students marked for Blended MOOCs Program', 7),
('14', 0, 'select 0 AS id,"Institute Name" as''A'',"CS101x" as''B'' ,"ME209x" as''C'', "EE210x" as''D'' union all select (@cnt := @cnt + 1) AS id,query.institutename,query.CS101x,query.ME209x,query.EE210x FROM (SELECT t.institutename, sum(if(s.courseid="IITBombayX/EE210.1xA15/2015_T1",1,0)) EE210x, sum(if(s.courseid="IITBombayX/ME209xA15/2015_T1",1,0)) ME209x, sum(if(s.courseid="IITBombayX/CS101.1xA15/2015_T1",1,0)) CS101x FROM SIP_studentdetails s, SIP_courselevelusers c, SIP_t10kt_institute t WHERE s.edxis_active =1 AND s.teacherid_id = c.id AND t.instituteid = c.instituteid_id AND c.instituteid_id !=0 group by t.institutename ORDER BY `t`.`institutename` ASC ) query CROSS JOIN (SELECT @cnt := 0) AS dummy', 'Student''s Participation:Institute wise Summary Report', 'Displays list of institutes with number of students participating in blended moocs program per course', 4),
('2', 0, 'select 0 AS id,"Email" as "A","Full Name" as "B","Institute Name" as "C","BMS Login" as "D" union all SELECT ( @cnt := @cnt +1 ) AS id, query.Email, query.Full_Name, query.Institute_Name, query.BMS_Login FROM ( SELECT p.email AS Email, concat( p.firstname, p.lastname ) AS Full_Name, i.institutename AS Institute_Name, if( l.status =0, "Not Activated", "Activated" ) "BMS_Login" FROM SIP_personinformation p LEFT OUTER JOIN edxapp.auth_user a ON a.email = p.email, SIP_institutelevelusers c, SIP_t10kt_institute i, SIP_userlogin l, auth_user au WHERE c.roleid = 2 AND c.personid_id = p.id AND p.instituteid_id = i.instituteid AND l.user_id = au.id AND p.email = au.email and i.instituteid != 0 order by i.institutename ) AS query CROSS JOIN ( SELECT @cnt :=0 ) AS dummy', 'Institute Heads: Status Report', 'Status Report of Head of the Institutes', 4),
('2_1_A', 2, 'select  0 AS id,"Course" as "A","Total" as "B","Enrolled" as "C","Unenrolled" as "D" union all SELECT ( @cnt := @cnt +1 ) AS id, query.Course_Id,query.Total,query.enrolled,query.unenrolled FROM( SELECT edxapp.student_courseenrollment.course_id AS Course_Id, sum(if(edxapp.student_courseenrollment.is_active=1,1,0))  as "enrolled" , sum(if(edxapp.student_courseenrollment.is_active=0,1,0)) as "unenrolled",count(*) as "Total"  FROM edxapp.student_courseenrollment  WHERE  edxapp.student_courseenrollment.course_id =''%s''   group by edxapp.student_courseenrollment.course_id order by Total) AS query CROSS JOIN ( SELECT @cnt :=0 ) AS dummy ', 'Course Participation Summary Report', 'Course Participation Summary Report', 4),
('2_1_B', 2, 'select  0 AS id,"Course" as "A",\r\n"Category"as B,\r\n"Total" as "C",\r\n"Enrolled" as "D",\r\n"Unenrolled" as "E" \r\nunion all \r\n(SELECT ( @cnt := @cnt +1 ) AS id, query.Course_Id,query.Category,query.Total,query.enrolled,query.unenrolled \r\nFROM( \r\nSELECT a.course_id AS Course_Id, (case c.personid_id \r\n  when 1 THEN "Unmarked" ELSE "Marked" END) as "Category", \r\nsum(if(a.is_active=1,1,0))  as "enrolled" , \r\nsum(if(a.is_active=0,1,0)) as "unenrolled",count(*) as "Total"  FROM edxapp.student_courseenrollment  a, SIP_studentdetails b, SIP_courselevelusers c ,SIP_edxcourses e \r\n  WHERE  a.course_id  = ''%s'' \r\n  and a.course_id=b.courseid \r\n  and  a.user_id=b.edxuserid_id  \r\n  and c.id=b.teacherid_id \r\n    and e.courseid=a.course_id \r\n  and c.courseid_id=e.id \r\n   group by case c.personid_id \r\n   when 1 THEN "Unmarked" ELSE "Marked" END \r\n   union all\r\n   SELECT a.course_id AS Course_Id, "Total" as Category ,\r\nsum(if(a.is_active=1,1,0))  as "enrolled" ,\r\n sum(if(a.is_active=0,1,0)) as "unenrolled"\r\n,count(*) as "Total"  FROM edxapp.student_courseenrollment a  \r\nWHERE  a.course_id = ''%s''\r\n   ) AS \r\nquery CROSS JOIN \r\n( SELECT @cnt :=0 ) AS dummy  )', 'Course Participation Summary Report', 'Course Participation Summary Report', 5),
('2_1_C', 2, 'select  0 AS id,"Course" as "A",\r\n"Institute"as B,\r\n"Total" as "C",\r\n"Enrolled" as "D",\r\n"Unenrolled" as "E" \r\nunion all \r\n(SELECT ( @cnt := @cnt +1 ) AS id, query.Course_Id,query.Institute,query.Total,query.enrolled,query.unenrolled \r\nFROM( \r\nSELECT a.course_id AS Course_Id, i.institutename as "Institute" ,\r\nsum(if(a.is_active=1,1,0))  as "enrolled" , \r\nsum(if(a.is_active=0,1,0)) as "unenrolled",count(*) as "Total"  FROM edxapp.student_courseenrollment  a, SIP_studentdetails b, SIP_courselevelusers c ,SIP_edxcourses e ,SIP_t10kt_institute i\r\n  WHERE  a.course_id  = ''%s'' \r\n  and a.course_id=b.courseid \r\n  and  a.user_id=b.edxuserid_id  \r\n  and c.id=b.teacherid_id \r\n    and e.courseid=a.course_id \r\n  and c.courseid_id=e.id \r\n  and c.instituteid_id  = i.instituteid\r\n   group by c.instituteid_id\r\n   union all\r\n   SELECT a.course_id AS Course_Id, "Total" as Category ,\r\nsum(if(a.is_active=1,1,0))  as "enrolled" ,\r\n sum(if(a.is_active=0,1,0)) as "unenrolled"\r\n,count(*) as "Total"  FROM edxapp.student_courseenrollment a  \r\nWHERE  a.course_id = ''%s''\r\n   ) AS \r\nquery CROSS JOIN \r\n( SELECT @cnt :=0 ) AS dummy  )', 'Course Participation Summary Report', 'Course Participation Summary Report', 5),
('3', 0, 'select  0 AS id,"Email" as "A","Full Name" as "B","Institute Name" as "C","BMS Login" as "D"\r\nunion all\r\nSELECT (\r\n@cnt := @cnt +1\r\n) AS id, query.Email, query.Full_Name, query.Institute_Name, query.BMS_Login\r\nFROM (\r\n\r\nSELECT p.email AS Email, concat( p.firstname, p.lastname ) AS Full_Name, i.institutename AS Institute_Name, if( l.status =0, "Not Activated", "Activated" ) "BMS_Login"\r\nFROM SIP_personinformation p\r\nLEFT OUTER JOIN edxapp.auth_user a ON a.email = p.email, SIP_institutelevelusers c, SIP_t10kt_institute i, SIP_userlogin l, auth_user au\r\nWHERE c.roleid =3\r\nAND c.personid_id = p.id\r\nAND p.instituteid_id = i.instituteid\r\nAND l.user_id = au.id\r\nAND p.email = au.email\r\nand i.instituteid != 0 order by i.institutename\r\n) AS query\r\nCROSS JOIN (\r\n\r\nSELECT @cnt :=0\r\n) AS dummy', 'Program Coordinators: Status Report', 'Status Report of Program Coordinators of Institutes', 4),
('4', 0, 'select  0 AS id,"Course" as "A","Total" as "B","Enrolled" as "C","Unenrolled" as "D" union all SELECT ( @cnt := @cnt +1 ) AS id, query.Course_Id,query.Total,query.enrolled,query.unenrolled FROM( SELECT edxapp.student_courseenrollment.course_id AS Course_Id, sum(if(edxapp.student_courseenrollment.is_active=1,1,0))  as "enrolled" , sum(if(edxapp.student_courseenrollment.is_active=0,1,0)) as "unenrolled",count(*) as "Total"  FROM edxapp.student_courseenrollment  WHERE  edxapp.student_courseenrollment.course_id in (''IITBombayX/ME209xA15/2015_T1'',''IITBombayX/EE210.1xA15/2015_T1'',''IITBombayX/CS101.1xA15/2015_T1'')   group by edxapp.student_courseenrollment.course_id order by Total) AS query CROSS JOIN ( SELECT @cnt :=0 ) AS dummy \n', 'Students'' Participation: Summary Report', 'Students'' Participation: Summary Report', 4),
('5', 0, 'select 0 AS id,"Course" as "A","Access_Count" as "B" union all SELECT (@cnt := @cnt +1) AS id, query.course_id,query.Access_Count FROM(SELECT edxapp.courseware_studentmodule.course_id AS course_id,count(*) AS Access_Count FROM edxapp.courseware_studentmodule WHERE edxapp.courseware_studentmodule.module_type = ''course'' AND edxapp.courseware_studentmodule.module_id in  ( "i4x://IITBombayX/CS101.1xA15/course/2015_T1",  "i4x://IITBombayX/ME209xA15/course/2015_T1",  "i4x://IITBombayX/EE210.1xA15/course/2015_T1")  group by module_id order by Access_Count DESC) AS query CROSS JOIN (SELECT @cnt :=0) AS dummy\r\n', 'Course Access: Summary Report', 'Number of users accessing respective courses in Blended MOOC system', 2),
('6', 0, 'select 0 AS id,"Course" as''A'',"RCID" as''B'' ,"Institute Name" as ''C'' ,"Email" as''D'',"Name" as ''E'' ,"#Students" as ''F'' union all  select (@cnt := @cnt + 1) AS id,query.course,query.rcid,query.institutename,query.email,query.name,query.student from  (SELECT  e.course, ai.remotecenterid_id rcid ,i.institutename,p.email,concat(p.firstname," ", p.lastname) name ,count(*) student FROM `SIP_studentdetails` s, SIP_courselevelusers c,SIP_edxcourses e,SIP_t10kt_institute i, SIP_personinformation p,SIP_t10kt_approvedinstitute  ai where s.teacherid_id=c.id and c.personid_id=p.id and p.instituteid_id =i.instituteid and  p.instituteid_id !=0 and  e.id=c.courseid_id and  p.instituteid_id= ai.instituteid_id group by c.courseid_id, e.course, p.email,p.firstname, p.lastname,p.instituteid_id ,i.institutename,ai.remotecenterid_id order by ai.remotecenterid_id,e.course, student DESC ) query  CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'Students'' Upload: Teachers'' Status Report', 'This is a summary report of students who have been marked by the teachers.', 6),
('7', 0, 'select 0 AS id,"Institiute Name" as''A'',"RCID" as''B'' ,"CS101.1xA15" as ''C'' ,"ME209.1xA15" as''D'',"EE210.1xA15" as ''E'' union all  select (@cnt := @cnt + 1) AS id,query.institutename,query.remotecenterid_id,query.cs,query.me,query.ee from (select b.institutename,remotecenterid_id,sum(if(courseid_id=6,teachers,0)) as cs ,sum(if(courseid_id=7,teachers,0)) as me,sum(if(courseid_id=8,teachers,0)) as ee  from (SELECT a.instituteid_id,a.remotecenterid_id,b.courseid_id,count(personid_id) teachers FROM `SIP_t10kt_approvedinstitute` a,SIP_courselevelusers b where  a.instituteid_id=b.instituteid_id and roleid = 5 and a.remotecenterid_id >1000 group by a.instituteid_id,a.remotecenterid_id,b.courseid_id ) query, SIP_t10kt_institute b WHERE instituteid_id=b.instituteid GROUP BY b.institutename,remotecenterid_id ORDER BY remotecenterid_id,cs DESC,me DESC,ee DESC) query  CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'Teachers'' Summary Report', 'Number of teachers participating in respective courses institute-wise', 5),
('8', 0, 'select 0 AS id," " as A,"CS101.1xA15" as''B'',"ME209xA15" as ''C'' ,"EE210.1xA15" as ''D'' union all select (@cnt := @cnt + 1) AS id,"No. of Institutes" a, query.cs,query.me,query.ee from (SELECT sum( if( courseid_id =6, 1, 0 ) ) as cs, sum( if( courseid_id =7, 1, 0 ) ) as me, sum( if( courseid_id =8, 1, 0 ) ) as ee FROM (SELECT a.instituteid_id, a.remotecenterid_id, b.courseid_id, count( personid_id ) teachers FROM `SIP_t10kt_approvedinstitute` a, SIP_courselevelusers b WHERE a.instituteid_id = b.instituteid_id AND roleid =5 AND a.remotecenterid_id >1000 GROUP BY a.instituteid_id, a.remotecenterid_id, b.courseid_id )q)query CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'Institutes'' Course Participation Report', 'Institutes'' participation count in each course', 4),
('9', 0, 'select 0 AS id,"Course" as A,"Male" as ''B'',"Female" as ''C'' ,"Others" as ''D'' ,"No Data" as''E'',"Total" as F union all  select (@cnt := @cnt + 1) AS id,query.course_id,query.Male,query.Female ,query.Others ,query.No_Data ,query.Total from (SELECT course_id,\r\nsum(if(gender=''Male'',1,0))  as Male ,\r\nsum(if(gender=''Female'',1,0))  as Female,\r\nsum(if(gender=''Others'',1,0))  as Others,\r\nsum(if(gender=''ND'',1,0))  as No_Data,\r\ncount(*) as Total\r\nfrom\r\n(SELECT a.user_id, a.course_id, if( b.gender = ''m'', "Male", if( b.gender = ''f'', "Female", if( b.gender = ''o'', "Others", "ND" ) ) ) Gender\r\nFROM edxapp.student_courseenrollment a, edxapp.auth_userprofile b\r\nWHERE a.course_id\r\nIN (\r\n''IITBombayX/ME209xA15/2015_T1'', ''IITBombayX/EE210.1xA15/2015_T1'', ''IITBombayX/CS101.1xA15/2015_T1''\r\n)\r\nAND a.user_id = b.user_id and a.is_active=1\r\n)  users group by course_id)query  CROSS JOIN (SELECT @cnt := 0) AS dummy;', 'User Profile: Gender-wise', '  User Profile: Gender-wise', 6);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
